#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACM | sed 's| |\\ |g')
FILES_TS=$(git diff --cached --name-only --diff-filter=ACM -- '*.ts' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES_TS" | xargs -L 100 node_modules/.bin/eslint --ext .ts --fix
echo "$FILES" | xargs -L 100 node_modules/.bin/prettier --write --ignore-unknown

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
