/**********************************************************************************************
Code generated by TrierDSL Plug-in
WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
  TngButtonModule,
  TngFilterPerfilModule,
  TngHotkeyModule,
  TngInputBooleanModule,
  TngInputNumberModule,
  TngInputTextModule,
  TngStickyModule,
  TngTableModule,
  TngTagModule,
} from '@triercloud/trier-ng';
import { CardModule } from 'primeng/card';
import { FilhoPrincipalModule } from '../components/filho-principal/filho-principal.module';
import { FilhoSecundarioModule } from '../components/filho-secundario/filho-secundario.module';
import { ProdutoDetalheModule } from '../produto-detalhe/produto-detalhe.module';
import { ProdutoCadastroComponent } from './produto-cadastro.component';
import { FormsModule } from '@angular/forms';

@NgModule({
  declarations: [ProdutoCadastroComponent],
  imports: [
    CommonModule,
    //TngPerfilModule.forRoot({ menuId }),
    TngFilterPerfilModule,
    TngTableModule,
    TngTagModule,
    TngStickyModule,
    TngButtonModule,
    TngHotkeyModule,
    ProdutoDetalheModule,
    FilhoPrincipalModule,
    FilhoSecundarioModule,
    CardModule,
    TngInputNumberModule,
    TngInputTextModule,
    TngInputBooleanModule,
    FormsModule,
  ],
  exports: [ProdutoCadastroComponent],
})
export class ProdutoCadastroModule {}
