/**********************************************************************************************
Code generated by TrierDSL Plug-in
WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
  TngButtonModule,
  TngFilterPerfilModule,
  TngHotkeyModule,
  TngPerfilModule,
  TngStickyModule,
  TngTableModule,
  TngTagModule,
} from '@triercloud/trier-ng';
import { ProdutoDetalheComponent } from './produto-detalhe.component';

@NgModule({
  declarations: [ProdutoDetalheComponent],
  imports: [
    CommonModule,
    //TngPerfilModule.forRoot({ menuId }),
    TngFilterPerfilModule,
    TngTableModule,
    TngTagModule,
    TngStickyModule,
    TngButtonModule,
    TngHotkeyModule,
  ],
  exports: [ProdutoDetalheComponent],
})
export class ProdutoDetalheModule {}
