/**********************************************************************************************
Code generated by TrierDSL Plug-in
WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { PermissionModule, ReadGuard, TngPerfilModule } from '@triercloud/trier-ng';
import { ProdutoDetalheComponent } from './produto-detalhe/produto-detalhe.component';
import { ProdutoListaComponent } from './produto-lista/produto-lista.component';
// Deve ser adicionado em forRoot
//  { path: 'produto', canActivate: [AuthGuard], loadChildren: () => import('./pages/produto/produto.module').then((m) => m.ProdutoModule), }

const menuId = 'e22b428f-d40f-327d-8259-add9e4dc17c5';
const routes: Routes = [
  {
    path: '',
    data: { breadcrumb: { label: 'Produto', id: menuId } },
    canActivate: [ReadGuard],
    children: [
      {
        path: '',
        component: ProdutoListaComponent,
        canActivate: [ReadGuard],
      },
      {
        path: 'produto-detalhe',
        component: ProdutoDetalheComponent,
        canActivate: [ReadGuard],
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes), PermissionModule.forRoot({ menuId }), TngPerfilModule.forRoot({ menuId })],
  exports: [RouterModule, PermissionModule],
})
export class ProdutoRoutingModule {}
