/**********************************************************************************************
Code generated by TrierDSL Plug-in
WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { AuthModule } from '@triercloud/trier-ng';

import { ProdutoListaModule } from './produto-lista/produto-lista.module';
import { ProdutoRoutingModule } from './produto-routing.module';
import { ProdutoService } from './services/produto.service';
import { CardModule } from 'primeng/card';

@NgModule({
  declarations: [],
  imports: [CommonModule, AuthModule, ProdutoRoutingModule, ProdutoListaModule, CardModule],
  exports: [],
  providers: [ProdutoService],
})
export class ProdutoModule {}
